owner: jupys 
repo: upptime 

sites:
  - name: main site
    url: https://jupy.wtf
  - name: Media
    url: $SECRET_HOME
    port: 35095
    check: "tcp-ping"

status-website:
  cname: status.jupy.wtf
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: jupy status
  introTitle: "**upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a simple status page which uses **real-time** data to show if my services are functioning as expected.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
